// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// NMF_optimized
Rcpp::List NMF_optimized(const arma::mat& X, int K, int maxiter, double tol);
RcppExport SEXP _scAB_NMF_optimized(SEXP XSEXP, SEXP KSEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(NMF_optimized(X, K, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// select_K_optimized
List select_K_optimized(const arma::mat& X, int K_max, int repeat_times, int maxiter, bool verbose);
RcppExport SEXP _scAB_select_K_optimized(SEXP XSEXP, SEXP K_maxSEXP, SEXP repeat_timesSEXP, SEXP maxiterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type repeat_times(repeat_timesSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(select_K_optimized(X, K_max, repeat_times, maxiter, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scAB_NMF_optimized", (DL_FUNC) &_scAB_NMF_optimized, 4},
    {"_scAB_select_K_optimized", (DL_FUNC) &_scAB_select_K_optimized, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_scAB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
