// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// guanrank_cpp
NumericVector guanrank_cpp(NumericMatrix mat_curve);
RcppExport SEXP _scAB_guanrank_cpp(SEXP mat_curveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_curve(mat_curveSEXP);
    rcpp_result_gen = Rcpp::wrap(guanrank_cpp(mat_curve));
    return rcpp_result_gen;
END_RCPP
}
// guanrank_complete_cpp
NumericMatrix guanrank_complete_cpp(NumericMatrix mat, bool complete);
RcppExport SEXP _scAB_guanrank_complete_cpp(SEXP matSEXP, SEXP completeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type complete(completeSEXP);
    rcpp_result_gen = Rcpp::wrap(guanrank_complete_cpp(mat, complete));
    return rcpp_result_gen;
END_RCPP
}
// NMF_optimized
Rcpp::List NMF_optimized(const arma::mat& X, int K, int maxiter, double tol);
RcppExport SEXP _scAB_NMF_optimized(SEXP XSEXP, SEXP KSEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(NMF_optimized(X, K, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// select_K_optimized
List select_K_optimized(const arma::mat& X, int K_max, int repeat_times, int maxiter, bool verbose, int n_threads);
RcppExport SEXP _scAB_select_K_optimized(SEXP XSEXP, SEXP K_maxSEXP, SEXP repeat_timesSEXP, SEXP maxiterSEXP, SEXP verboseSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type repeat_times(repeat_timesSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(select_K_optimized(X, K_max, repeat_times, maxiter, verbose, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// scAB_inner
List scAB_inner(const arma::sp_mat& X, const arma::sp_mat& A, const arma::sp_mat& D, const arma::sp_mat& L, const arma::sp_mat& S, int K, double alpha, double alpha_2, int maxiter, double convergence_threshold);
RcppExport SEXP _scAB_scAB_inner(SEXP XSEXP, SEXP ASEXP, SEXP DSEXP, SEXP LSEXP, SEXP SSEXP, SEXP KSEXP, SEXP alphaSEXP, SEXP alpha_2SEXP, SEXP maxiterSEXP, SEXP convergence_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_2(alpha_2SEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type convergence_threshold(convergence_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(scAB_inner(X, A, D, L, S, K, alpha, alpha_2, maxiter, convergence_threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scAB_guanrank_cpp", (DL_FUNC) &_scAB_guanrank_cpp, 1},
    {"_scAB_guanrank_complete_cpp", (DL_FUNC) &_scAB_guanrank_complete_cpp, 2},
    {"_scAB_NMF_optimized", (DL_FUNC) &_scAB_NMF_optimized, 4},
    {"_scAB_select_K_optimized", (DL_FUNC) &_scAB_select_K_optimized, 6},
    {"_scAB_scAB_inner", (DL_FUNC) &_scAB_scAB_inner, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_scAB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
