# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NMF_optimized <- function(X, K, maxiter = 2000L, tol = 1e-5) {
    .Call('_scAB_NMF_optimized', PACKAGE = 'scAB', X, K, maxiter, tol)
}

select_K_optimized <- function(X, K_max = 20L, repeat_times = 10L, maxiter = 2000L, verbose = TRUE) {
    .Call('_scAB_select_K_optimized', PACKAGE = 'scAB', X, K_max, repeat_times, maxiter, verbose)
}

