# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

guanrank_cpp <- function(mat_curve) {
    .Call('_scAB_guanrank_cpp', PACKAGE = 'scAB', mat_curve)
}

guanrank_complete_cpp <- function(mat, complete = FALSE) {
    .Call('_scAB_guanrank_complete_cpp', PACKAGE = 'scAB', mat, complete)
}

NMF_optimized <- function(X, K, maxiter = 2000L, tol = 1e-5) {
    .Call('_scAB_NMF_optimized', PACKAGE = 'scAB', X, K, maxiter, tol)
}

select_K_optimized <- function(X, K_max = 20L, repeat_times = 10L, maxiter = 2000L, verbose = TRUE) {
    .Call('_scAB_select_K_optimized', PACKAGE = 'scAB', X, K_max, repeat_times, maxiter, verbose)
}

scAB_inner <- function(X, A, D, L, S, K, alpha = 0.005, alpha_2 = 0.005, maxiter = 2000L, convergence_threshold = 1e-5) {
    .Call('_scAB_scAB_inner', PACKAGE = 'scAB', X, A, D, L, S, K, alpha, alpha_2, maxiter, convergence_threshold)
}

